#!/bin/sh /etc/rc.common

START=21
STOP=89

USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/pwm-fan.sh
    procd_set_param respawn
    procd_close_instance
}